### ISSUE TITLE
Unable to build on node 4.4.5 and MacOS 10.14.5 and xcode-select installed

### ISSUE THREAD

**Issue by whiteboardmonk** [advertine/node-ip2location#5]
I'm getting the following error during npm install. 
```
  CXX(target) Release/obj.target/nodeip2location/src/nodeip2location.o
warning: include path for stdlibc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
In file included from ../src/nodeip2location.cc:1:
In file included from ../src/nodeip2location.h:4:
../node_modules/nan/nan.h:57:10: fatal error: 'algorithm' file not found
#include <algorithm>
         ^~~~~~~~~~~
```

On googling it seems this is related to the deprecated / path issues for libstdc++. 

Any help or workaround would be greatly appreciated.

**Comment by whiteboardmonk** [comment]
More info - https://docs.brew.sh/C++-Standard-Libraries

**Comment by royaltm** [comment]
node 4 is no more supported, try some of the previous versions of node-ip2location, e.g. "1.1.3"

**Comment by royaltm** [comment]
No further feedback. I hope @whiteboardmonk you have resolved your issue.
